//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrunTakipSitesi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSatis
    {
        public int Satisid { get; set; }
        public Nullable<int> Urun { get; set; }
        public Nullable<byte> Personel { get; set; }
        public Nullable<int> Musteri { get; set; }
        public decimal Fiyat { get; set; }
    
        public virtual TblMusteri TblMusteri { get; set; }
        public virtual TblPersonel TblPersonel { get; set; }
        public virtual TblUrunler TblUrunler { get; set; }
    }
}
